spring.application.name=API-de-Gerenciamento-de-Consultas

# Configuração do Banco de Dados Temporário (H2) para testes locais
spring.datasource.url=jdbc:h2:mem:clinica_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Diz ao Hibernate para criar as tabelas automaticamente
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true